version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./app/licsss-component-v1
        target: /usr/src/app
    command: sh -c "npm run storybook -s ./src"
    ports:
      - 3000:3000
      - 6006:6006
    stdin_open: true #標準入力をコンテナと紐付ける
